# https://github.com/SonarSource/sonarcloud-github-action
# https://sonarcloud.io/documentation/analysis/analysis-parameters/

name: Anaylse with SonarCloud

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sonarCloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=gmuth
          -Dsonar.projectKey=gmuth_ipp-client-kotlin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
