# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      # https://github.com/gradle/gradle-build-action
      - name: Setup build cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with gradle wrapper
        run: ./gradlew build
#      - name: Publish GitHub Packages
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        run: ./gradlew publish
      - name: Analyse with SonarQube
#        run: ./gradlew test jacocoTestReport sonarqube
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}