# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

name: Publish

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: --console=plain build
      - name: Gradle publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gradle -Drepo=github publish
